module.exports = [
  "Coconut Milk",
  "Bagoong",
  "Maggi Magic Sarap",
  "Vinegar",
  "Soy Sauce",
  "Sinigang Mix",
  "Fish Sauce",
  "Oyster Sauce",
  "Mushroom",
  "All Purpose Flour",
  "Black Pepper",
  "Salt",
  "Corn",
  "All Purpose Cream",
  "Rice",
  "Bihon",
  "Laurel Leaves",
  "Garlic Powder",
  "Cornstarch",
  "Tomato Sauce",
  "Tomato Paste",
  "Liver Spread",
  "Shrimp Paste",
  "Chicken Cubes",
  "Pork Cubes",
  "Beef Cubes",
  "Spaghetti",
  "Sotanghon",
];