name: Daily DA Scraper

on:

  schedule:
    - cron: "0 16 * * *"

  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./scraper

      - name: Check Supabase secrets
        run: |
          if [ -z "$SUPABASE_URL" ]; then
            echo "SUPABASE_URL is MISSING"
          else
            echo "SUPABASE_URL is available"
          fi

          if [ -z "$SUPABASE_KEY" ]; then
            echo "SUPABASE_KEY is MISSING"
          else
            echo "SUPABASE_KEY is available"
          fi

      - name: Run scraper
        run: node index.js
        working-directory: ./scraper